- name: demo on shell vs command
  hosts: local
  connection: local
  tasks:
  - name: comand test
    command: cat /etc/passwd | grep root
    #shell: cat /etc/passwd | grep root
    register: users_output

  - name: print output
    debug:
      msg: "{{users_output}}"

  #- name: list_files
  #    command: ls -ltr > /tmp/files.txt