[frontend]
172.31.5.107 COURSE="DEVSecOPS"
172.31.4.31  COURSE="DEVAIOPS"
[cart]
172.31.2.15
[catalog]
172.31.2.16
[shipping]
172.31.2.17
[local]
localhost

;group of groups
[frontend:vars]
TRAINER= "Mohan"
DURATION= "2 MONTHS"